version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  ypmetricssrv:
    image: ypmetricssrv
    ports:
      - 8080:8080
      - 18080:18080
    container_name: ypmetricssrv
    hostname: ypmetricssrv
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      ADDRESS: ":8080"
      #DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/postgres"
    networks:
      - default

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - default

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

networks:
  default:
    driver: bridge